[{
    "company_name":"hcl",
    "date":ISODate("2020-09-25"),
    "students_appeared":"Nithish,dineshwaran,ronaldo,dhoni,virat"
},
{
    "company_name":"cts",
    "date":ISODate("2020-10-16"),
    "students_appeared":"anabel,sanjay,ebin,Jasprit,raina"
},
{
    "company_name":"tcs",
    "date":ISODate("2020-10-27"),
    "students_appeared":"virat,rohit,Nithish,virat,abi"
},
{
    "company_name":"zoho",
    "date":ISODate("2020-11-15"),
    "students_appeared":"naveen,suvan,felix,jethro,ashwin"
},
{
    "company_name":"guvi",
    "date":ISODate("2020-11-25"),
    "students_appeared":"jeshwin,jack,rohit,yogesh,edwin"
}]